version: "3"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ${Y3S_DIRECTORY}/movies:/data/movies
      - ${Y3S_DIRECTORY}/tvshows:/data/tvshows
      - ${Y3S_DIRECTORY}/books:/data/books
      - ${Y3S_DIRECTORY}/audiobooks:/data/audiobooks
      - ${Y3S_DIRECTORY}/config/jellyfin:/config
    ports:
      - 8096:8096
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.0
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
    volumes:
      - ${Y3S_DIRECTORY}/downloads:/downloads
      - ${Y3S_DIRECTORY}/config/qbittorrent:/config
    restart: unless-stopped
    ports:
      - 8080:8080
    network_mode: "service:gluetun"

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${Y3S_DIRECTORY}/tvshows:/tv
      - ${Y3S_DIRECTORY}/downloads:/downloads
      - ${Y3S_DIRECTORY}/config/sonarr:/config
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${Y3S_DIRECTORY}/movies:/movies
      - ${Y3S_DIRECTORY}/downloads:/downloads
      - ${Y3S_DIRECTORY}/config/radarr:/config
    ports:
      - 7878:7878
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${Y3S_DIRECTORY}/music:/music
      - ${Y3S_DIRECTORY}/downloads:/downloads
      - ${Y3S_DIRECTORY}/config/lidarr:/config
    ports:
      - 8686:8686
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${Y3S_DIRECTORY}/books:/books
      - ${Y3S_DIRECTORY}/audiobooks:/audiobooks
      - ${Y3S_DIRECTORY}/downloads:/downloads
      - ${Y3S_DIRECTORY}/config/readarr:/config
    ports:
      - 8787:8787
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${Y3S_DIRECTORY}/movies:/movies
      - ${Y3S_DIRECTORY}/tvshows:/tv
      - ${Y3S_DIRECTORY}/config/bazarr:/config
    ports:
      - 6767:6767
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${Y3S_DIRECTORY}/config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun:v3.34.1
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8080:8080/tcp # gluetun
    volumes:
      - ${Y3S_DIRECTORY}/config/gluetun:/config
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE}
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - OPENVPN_CIPHERS=AES-256-GCM
      - SERVER_HOSTNAMES=${VPN_HOSTNAME}
      - VPN_PORT_FORWARDING=on
    restart: unless-stopped
